CREATE PROC SP_LUONGNGUOIHOC
AS 
BEGIN
	SELECT
		YEAR(NGAYDK) NAM,
		COUNT(*) SOLUONG,
		MIN(NGAYDK) DAUTIEN,
		MAX(NGAYDK) CUOICUNG
	FROM NGUOIHOC
	GROUP BY YEAR(NGAYDK)
END
GO
CREATE PROC SP_BANGDIEM(@MAKH INT)
AS 
BEGIN
	SELECT
		NH.MANH,
		NH.HOTEN,
		HV.DIEM
	FROM HOCVIEN HV
	JOIN NGUOIHOC NH ON NH.MANH = HV.MANH
	WHERE HV.MAKH = @MAKH
	ORDER BY HV.DIEM DESC
END
GO
CREATE PROC SP_THONGKEDIEM
AS 
BEGIN
	SELECT
		TENCD CHUYENDE,
		COUNT(MANH) SOHV,
		MIN(DIEM) THAPNHAT,
		MAX(DIEM) CAONHAT,
		AVG(DIEM) TRUNGBINH
	FROM KHOAHOC KH
	JOIN HOCVIEN HV ON KH.MAKH = HV.MAKH
	JOIN CHUYENDE CD ON CD.MACD = KH.MACD
	GROUP BY TENCD
END
GO
CREATE PROC SP_THONGKEDOANHTHU(@YEAR INT)
AS 
BEGIN
	SELECT
		TENCD,
		COUNT(DISTINCT KH.MAKH) SOKH,
		COUNT(HV.MAHV) SOHV,
		SUM(KH.HOCPHI) DOANHTHU,
		MIN(KH.HOCPHI) THAPNHAT,
		MAX(KH.HOCPHI) CAONHAT,
		AVG(KH.HOCPHI) TRUNGBINH
	FROM KHOAHOC KH
	JOIN HOCVIEN HV ON KH.MAKH = HV.MAKH
	JOIN CHUYENDE CD ON CD.MACD = KH.MACD
	WHERE YEAR(NGAYKG) = @YEAR
	GROUP BY TENCD
END
GO
CREATE PROC SP_THONGKENGUOIHOC
AS 
BEGIN
	SELECT
		YEAR(NGAYDK) NAM,
		COUNT(*) SOLUONG,
		MIN(NGAYDK) DAUTIEN,
		MAX(NGAYDK) CUOIDUNG
	FROM NGUOIHOC
	GROUP BY YEAR(NGAYDK)
END

--INSERT INTO CHUYENDE(MACD, TENCD, THOILUONG, HINH, MOTA) VALUES (?, ?, ?, ?, ?)
--UPDATE CHUYENDE SET MACD = ?, TENCD = ?, HOCPHI = ?, THOILUONG = ?, HINH = ?, MOTA = ? WHERE MACD = ?
--DELETE FROM CHUYENDE WHERE MACD = ?
--SELECT * FROM CHUYENDE WHERE MACD = ?