--CREATE DATABASE EDUSYS
CREATE TABLE NHANVIEN(
MANV NVARCHAR(20) NOT NULL PRIMARY KEY,
MATKHAU NVARCHAR(50) NOT NULL,
HOTEN NVARCHAR(50) NOT NULL,
VAITRO BIT DEFAULT 0
)

CREATE TABLE CHUYENDE(
MACD NCHAR(5) NOT NULL PRIMARY KEY,
TENCD NVARCHAR(50) NOT NULL,
HOCPHI FLOAT NOT NULL,
THOILUONG INT NOT NULL,
HINH NVARCHAR(50) NOT NULL,
MOTA NVARCHAR(255) NOT NULL,
)

CREATE TABLE KHOAHOC(
MAKH	INT IDENTITY(1,1) PRIMARY KEY,
MACD	NCHAR(5) NOT NULL,
HOCPHI	FLOAT NOT NULL,
THOILUONG INT NOT NULL,
NGAYKG DATE NOT NULL,
GHICHU NVARCHAR(255) NOT NULL,
MANV NVARCHAR(20) NOT NULL,
NGAYTAO DATE DEFAULT GETDATE(),
CONSTRAINT FK_KHOAHOC_CHUYENDE FOREIGN KEY (MACD)
REFERENCES CHUYENDE(MACD)
ON DELETE NO ACTION
ON UPDATE CASCADE,
CONSTRAINT FK_KHOAHOC_NHANVIEN FOREIGN KEY (MANV)
REFERENCES NHANVIEN(MANV)
ON DELETE NO ACTION
ON UPDATE CASCADE,
)

CREATE TABLE NGUOIHOC(
MANH NCHAR(7) NOT NULL PRIMARY KEY,
HOTEN NVARCHAR(50) NOT NULL,
GIOITINH BIT DEFAULT 1,
NGAYSINH DATE NOT NULL,
DIENTHOAI NVARCHAR(24) NOT NULL,
EMAIL NVARCHAR(50) NOT NULL,
GHICHU NVARCHAR(255) NULL,
MANV NVARCHAR(20) NOT NULL,
NGAYDK DATE DEFAULT GETDATE(),
CONSTRAINT FK_NGUOIHOC_NHANVIEN FOREIGN KEY (MANV)
REFERENCES NHANVIEN(MANV)
ON DELETE NO ACTION
ON UPDATE CASCADE
)

CREATE TABLE HOCVIEN(
MAHV INT IDENTITY(1,1) PRIMARY KEY,
MAKH INT NOT NULL,
MANH NCHAR(7) NOT NULL,
DIEM FLOAT DEFAULT 1,
CONSTRAINT FK_HOCVIEN_KHOAHOC FOREIGN KEY (MAKH)
REFERENCES KHOAHOC(MAKH)
ON DELETE CASCADE
ON UPDATE CASCADE,
CONSTRAINT FK_HOCVIEN_NGUOIHOC FOREIGN KEY (MANH)
REFERENCES NGUOIHOC(MANH)
)